### ISSUE TITLE
License of the repo unclear

### ISSUE THREAD

**Issue by christian-krieg** [Architech-Silica/Designing-a-Custom-AXI-Slave-Peripheral#2]
Hi!

I am interested in using some code of your repo. Therefore, I am wondering under which license your repository is published? Could you please clarify this issue by putting a file named "LICENSE" to the top-level directory of your repo, containing the license text? A permissive license such as BSD, MIT, or ISC license is highly appreciated :)

Cheers,
Christian

**Comment by Q-Branch** [comment]
Licence Added.
